dist: trusty
sudo: false
language: cpp
before_script:
- git checkout master
- git submodule init
- git submodule update
- git submodule foreach git pull origin master
script:
- git add -A
- git commit -m "update head [ci skip]" || true
- git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git ${TRAVIS_BRANCH}
env:
  global:
  - secure: 0RtCIFfvMaek3oDbYN4mjQ2JFSiXaFH5G0WACnokWpqdakF9jXSM23EAiKl8en15DGyTX9JJKEbjs747GFcmPJvpFPPrSqIA0sfPPNDpW4jVssprJYDPYH6CuemgGizWT9LzxCoLaMA/ypDf9t9b/g0puh8dElfF8k0oTdpXaebKpwojl/DXYB/Tsn9zKT4tVEoS8z7JAmn7dvFejUqfZZfngIsI5aKLFTfX0AFIcaKbYiieT/5ndoa0ZJi3GKW6bgNyso2BBmgu2YLx8j8UsFdZr9fY8rS/m5bB4eaYJNnqA6aliIzo1XUE/zbJi2peKdFsds4YuF/0+FcW/WUmpnrlndtCYhGMgjB5/8jITzS7oDak4fY5pzErQu47adz9uJlaBCl3N8JQFstK0PHeKdAbY8XXPp6vh37KXR0EcLQnF7mOiqPtQglDKOR4HVWXce5aT45MD1/AtxGHszWMQ/E9q4unSJMBAJRfkev70NlnJcvfn2kx3SN169o24qlubh+Z5+lIh2VuCFMTA6GfCoLks87WU6ATVQcDbtQjLcT3LeUpYqioopG4T2afyENh5O98dlvPohU67GaHbZyqQ6UlNmb3d/P68QuniIRP5daocnys5Z53x3ctxOuuNUV5FbcsF58aDI/PWzjqLhyQ/BA0g8VIYJHjgrluou3xin4=
